name: CI

on:
  push:
    branches:
      - stable
      - dev
      - docs

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-and-test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      TMPDIR: /tmp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python (${{ matrix.python-version }}) for ${{ matrix.os }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install library dependencies
        run: python -m pip install -Ur requirements.txt

      - name: Install library
        run: python -m pip install -e .
      
      - name: "Invoke sphinx-build to build the HTML docs"
        run: |
          python -m pip install -Ur docs/requirements.txt
          sphinx-build -W -b html -d ${{ env.TMPDIR }}/doctrees source ${{ env.TMPDIR }}/html
