name: Package Build and Test

on:
  push:
    branches: [ 'stable' ]
  pull_request:
    branches: [ 'stable', 'dev' ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
        cache: 'pip'

    - name: Install production dependencies
      run: |
        python -m pip install .

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
        cache: 'pip'

    - name: Install production and testing dependencies
      run: python -m pip install .[test]

    - name: Test with PyTest
      run: python -m pytest --color=yes --capture=no --cov-config=.coveragerc --cov-report=lcov --cov=src/ccanvas
