name: Update package version

on:
  release:
    types: [published]

jobs:

  update-package-version:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - uses: actions/checkout@v3

    - name: Update pyproject.toml version
      run: |
        git clone https://gist.github.com/a66c601b7ebab8dc9370348697e540d1.git
        version=${{github.ref}}
        python3 a66c601b7ebab8dc9370348697e540d1/pytoml-version-updater.py ${version#refs/tags/v}

    - name: Config git
      run: |
        git config --global user.email "dev.szblzpaulo@gmail.com"
        git config --global user.name "Paulo Sánchez"

    - name: Commit and push pyproject.toml modifications
      run: |
        version=${{github.ref}}
        git commit pyproject.toml -m "Bump version to ${version#refs/tags/v}"
        git push --force origin HEAD:stable
